"""Exact augmented-lattice post-processing for Regev-style samples.

Let the measured integer rows be ``k_i`` and let ``w_i = k_i / M``.  Regev's
post-processing lattice is generated by the *columns* of

    B = [[I_d, 0],
         [S W, S I_m]],

where the rows of ``W`` are the ``w_i`` and theoretically ``S = delta**-1``
for a proven torus-noise bound ``delta``.  If ``S = p/q`` in lowest terms,
this module gives SymPy the integer row basis

    A = (q M B).T = [[q M I_d, p K.T],
                      [0,       p M I_m]],

where ``K`` has rows ``k_i``.  Multiplication by the common scalar ``q M``
does not change the reduction geometry.  SymPy reduces rows, and its
unimodular transform exposes the first ``d`` coefficients, which are exactly
the candidate relation ``z``.

The module deliberately does not derive roots with ``sqrt(base)``, compute
orders, or accept a factorization of ``N``.  Complete factor extraction
requires explicit stored roots ``b_i`` and verifies ``b_i**2 == a_i (mod N)``.

Limitations
-----------
The guarantees in Regev's Lemma 4.4 require at least ``d + 4`` independent
samples that are close to uniform dual-lattice cosets and a justified noise
bound.  The supplied notebook instead uses a uniform hard window, so callers
must provide the scale (or an exact rational noise bound), and success on its
samples is empirical.  The primary endpoint applies the Gram--Schmidt prefix
cutoff in Regev's Claim 5.1 and verifies its projected vectors exactly in
``L``.  All reduced-basis rows are also scanned, but only as a separately
labelled diagnostic.  The implementation does not enumerate arbitrary short
combinations, so failure to find a relation is not evidence that none exists.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import gcd
from operator import index
from typing import Sequence

from .core import RootedBaseFamily, modular_product


@dataclass(frozen=True)
class AugmentedLattice:
    """An exact integer presentation of Regev's rational lattice."""

    samples: tuple[tuple[int, ...], ...]
    modulus: int
    dimension: int
    sample_count: int
    scale: Fraction
    clearing_factor: int
    integer_row_basis: tuple[tuple[int, ...], ...]


@dataclass(frozen=True)
class LLLReduction:
    """A reduced row basis and the unimodular row transformation."""

    reduced_rows: tuple[tuple[int, ...], ...]
    transform_rows: tuple[tuple[int, ...], ...]
    delta: Fraction
    backend: str


@dataclass(frozen=True)
class Claim51Prefix:
    """The exact Gram--Schmidt cutoff prescribed by Regev's Claim 5.1."""

    embedding_norm_bound: Fraction
    lattice_dimension: int
    gram_schmidt_squared_norms: tuple[Fraction, ...]
    cleared_cutoff_squared: Fraction
    prefix_length: int


@dataclass(frozen=True)
class RelationClassification:
    """Membership in ``L_0`` and any factor obtained from ``L \\ L_0``."""

    relation: tuple[int, ...]
    root_product: int
    relation_class: str
    gcd_minus: int
    gcd_plus: int
    factor_pair: tuple[int, int] | None


@dataclass(frozen=True)
class LatticeRelationCandidate:
    """An exactly verified relation projected from a reduced lattice row."""

    relation: tuple[int, ...]
    source_row: int
    cleared_embedding_vector: tuple[int, ...]
    cleared_squared_norm: int
    embedding_squared_norm: Fraction
    root_product: int
    relation_class: str
    factor_pair: tuple[int, int] | None


@dataclass(frozen=True)
class LatticePostprocessingResult:
    """Complete samples-to-factor result with auditable intermediate state."""

    embedding: AugmentedLattice
    reduction: LLLReduction
    claim_prefix: Claim51Prefix
    claim_prefix_candidates: tuple[LatticeRelationCandidate, ...]
    all_basis_diagnostic_candidates: tuple[LatticeRelationCandidate, ...]
    factor_pair: tuple[int, int] | None
    all_basis_diagnostic_factor_pair: tuple[int, int] | None
    claim_prefix_zero_projection_rows: int
    claim_prefix_rejected_nonrelation_rows: int
    all_basis_zero_projection_rows: int
    all_basis_rejected_nonrelation_rows: int

    @property
    def candidates(self) -> tuple[LatticeRelationCandidate, ...]:
        """Compatibility alias for the primary Claim 5.1 candidates."""

        return self.claim_prefix_candidates


def _as_integer(value: object, name: str) -> int:
    if isinstance(value, bool):
        raise TypeError(f"{name} must be an integer, not bool")
    try:
        return int(index(value))
    except TypeError as exc:
        raise TypeError(f"{name} must be an integer") from exc


def _as_fraction(value: int | Fraction, name: str) -> Fraction:
    if isinstance(value, bool) or not isinstance(value, (int, Fraction)):
        raise TypeError(f"{name} must be an int or fractions.Fraction")
    result = Fraction(value)
    if result <= 0:
        raise ValueError(f"{name} must be positive")
    return result


def _normalize_samples(
    samples: Sequence[Sequence[int]], modulus: int
) -> tuple[tuple[int, ...], ...]:
    rows = tuple(
        tuple(_as_integer(value, f"samples[{i}][{j}]") for j, value in enumerate(row))
        for i, row in enumerate(samples)
    )
    if not rows or not rows[0]:
        raise ValueError("samples must be a nonempty m-by-d matrix")
    dimension = len(rows[0])
    if any(len(row) != dimension for row in rows):
        raise ValueError("all sample rows must have the same dimension")
    if any(value < 0 or value >= modulus for row in rows for value in row):
        raise ValueError("sample coordinates must lie in {0, ..., modulus - 1}")
    return rows


def build_augmented_lattice(
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    require_regev_sample_count: bool = True,
) -> AugmentedLattice:
    """Build the exact integer row basis ``(q M B).T``.

    Exactly one of ``scale`` and ``noise_bound`` is required.  Passing
    ``noise_bound=delta`` selects Regev's ``S = 1/delta``.  Floats are rejected
    so that the basis cannot silently depend on binary rounding.
    """

    modulus = _as_integer(modulus, "modulus")
    if modulus <= 1:
        raise ValueError("modulus must be greater than one")
    if (scale is None) == (noise_bound is None):
        raise ValueError("provide exactly one of scale or noise_bound")
    if noise_bound is not None:
        scale_fraction = 1 / _as_fraction(noise_bound, "noise_bound")
    else:
        scale_fraction = _as_fraction(scale, "scale")  # type: ignore[arg-type]

    rows = _normalize_samples(samples, modulus)
    sample_count = len(rows)
    dimension = len(rows[0])
    if require_regev_sample_count and sample_count < dimension + 4:
        raise ValueError(
            f"Regev reconstruction requires at least d + 4 = {dimension + 4} samples"
        )

    p = scale_fraction.numerator
    q = scale_fraction.denominator
    clearing_factor = q * modulus
    lattice_dimension = dimension + sample_count

    integer_basis: list[tuple[int, ...]] = []
    for coordinate in range(dimension):
        top = [clearing_factor if j == coordinate else 0 for j in range(dimension)]
        bottom = [p * row[coordinate] for row in rows]
        integer_basis.append(tuple(top + bottom))
    for sample_index in range(sample_count):
        row = [0] * lattice_dimension
        row[dimension + sample_index] = p * modulus
        integer_basis.append(tuple(row))

    return AugmentedLattice(
        samples=rows,
        modulus=modulus,
        dimension=dimension,
        sample_count=sample_count,
        scale=scale_fraction,
        clearing_factor=clearing_factor,
        integer_row_basis=tuple(integer_basis),
    )


def lll_reduce_augmented_lattice(
    embedding: AugmentedLattice, delta: Fraction = Fraction(3, 4)
) -> LLLReduction:
    """LLL-reduce the embedding exactly with SymPy's integer row backend."""

    delta = _as_fraction(delta, "delta")
    if not Fraction(1, 4) < delta < 1:
        raise ValueError("LLL delta must be strictly between 1/4 and 1")
    try:
        from sympy import Matrix, Rational
    except ImportError as exc:  # pragma: no cover - the research environment pins SymPy.
        raise RuntimeError("SymPy is required for exact LLL reduction") from exc

    basis = Matrix(embedding.integer_row_basis)
    reduced, transform = basis.lll_transform(
        delta=Rational(delta.numerator, delta.denominator)
    )
    if transform * basis != reduced:
        raise ArithmeticError("LLL backend returned an inconsistent transformation")
    return LLLReduction(
        reduced_rows=tuple(tuple(int(value) for value in row) for row in reduced.tolist()),
        transform_rows=tuple(
            tuple(int(value) for value in row) for row in transform.tolist()
        ),
        delta=delta,
        backend="sympy.Matrix.lll_transform",
    )


def _gram_schmidt_squared_norms(
    rows: Sequence[Sequence[int]],
) -> tuple[Fraction, ...]:
    """Return exact squared norms of the row Gram--Schmidt vectors."""

    orthogonal: list[tuple[Fraction, ...]] = []
    squared_norms: list[Fraction] = []
    for row in rows:
        vector = [Fraction(value) for value in row]
        for previous, previous_norm in zip(
            orthogonal, squared_norms, strict=True
        ):
            coefficient = sum(
                value * basis_value
                for value, basis_value in zip(vector, previous, strict=True)
            ) / previous_norm
            vector = [
                value - coefficient * basis_value
                for value, basis_value in zip(vector, previous, strict=True)
            ]
        squared_norm = sum(value * value for value in vector)
        if squared_norm == 0:
            raise ArithmeticError("reduced lattice basis is not full row rank")
        orthogonal.append(tuple(vector))
        squared_norms.append(squared_norm)
    return tuple(squared_norms)


def claim_5_1_prefix(
    embedding: AugmentedLattice,
    reduction: LLLReduction,
    norm_bound: int | Fraction,
) -> Claim51Prefix:
    """Return Claim 5.1's LLL prefix with integer scaling accounted for.

    ``norm_bound`` is Regev's ``T`` for vectors in the *unscaled augmented
    lattice* ``B``.  If a relation-lattice bound ``T_L`` is used with
    Corollary 4.5, the corresponding augmented bound is
    ``sqrt(d + 5) * T_L``; callers must supply an exact rational bound or an
    explicit rational upper bound.

    For lattice dimension ``k``, Claim 5.1 stops before the first row whose
    Gram--Schmidt norm is at least ``2**(k/2) * T``.  Our integer basis is the
    rational lattice multiplied by ``embedding.clearing_factor``, so squared
    norms are compared exactly against

        clearing_factor**2 * 2**k * T**2.
    """

    norm_bound = _as_fraction(norm_bound, "norm_bound")
    lattice_dimension = embedding.dimension + embedding.sample_count
    if len(reduction.reduced_rows) != lattice_dimension:
        raise ValueError("reduction dimension does not match the embedding")
    if any(len(row) != lattice_dimension for row in reduction.reduced_rows):
        raise ValueError("reduced basis must be square in the embedding dimension")

    squared_norms = _gram_schmidt_squared_norms(reduction.reduced_rows)
    cutoff_squared = (
        embedding.clearing_factor**2
        * (1 << lattice_dimension)
        * norm_bound**2
    )
    prefix_length = lattice_dimension
    for row_index, squared_norm in enumerate(squared_norms):
        if squared_norm >= cutoff_squared:
            prefix_length = row_index
            break
    return Claim51Prefix(
        embedding_norm_bound=norm_bound,
        lattice_dimension=lattice_dimension,
        gram_schmidt_squared_norms=squared_norms,
        cleared_cutoff_squared=cutoff_squared,
        prefix_length=prefix_length,
    )


def _normalize_modular_inputs(
    N: int,
    bases: Sequence[int],
    stored_roots: Sequence[int],
    dimension: int,
) -> tuple[int, tuple[int, ...], tuple[int, ...]]:
    N = _as_integer(N, "N")
    if N <= 2 or N % 2 == 0:
        raise ValueError("Regev square-root extraction expects an odd N greater than two")
    if len(bases) != dimension or len(stored_roots) != dimension:
        raise ValueError("bases and stored_roots must both have sample dimension d")
    normalized_bases = tuple(_as_integer(a, f"bases[{i}]") % N for i, a in enumerate(bases))
    normalized_roots = tuple(
        _as_integer(b, f"stored_roots[{i}]") % N for i, b in enumerate(stored_roots)
    )
    for i, (a, b) in enumerate(zip(normalized_bases, normalized_roots, strict=True)):
        if gcd(a, N) != 1 or gcd(b, N) != 1:
            raise ValueError(f"base/root pair {i} must consist of units modulo N")
        if b * b % N != a:
            raise ValueError(
                f"stored_roots[{i}] is not provenance for bases[{i}] modulo N"
            )
    return N, normalized_bases, normalized_roots


def _classify_relation_with_stored_roots(
    N: int,
    bases: Sequence[int],
    stored_roots: Sequence[int],
    relation: Sequence[int],
) -> RelationClassification:
    """Verify ``z in L`` and classify it as ``L_0`` or ``L \\ L_0``.

    The only square roots used are ``stored_roots`` supplied by the caller and
    checked against the circuit bases.  No root, order, or factor is inferred
    before the final GCD extraction.
    """

    z = tuple(_as_integer(value, f"relation[{i}]") for i, value in enumerate(relation))
    N, normalized_bases, normalized_roots = _normalize_modular_inputs(
        N, bases, stored_roots, len(z)
    )
    if not any(z):
        raise ValueError("the zero vector is not a factoring relation")
    if modular_product(N, normalized_bases, z) != 1:
        raise ValueError("relation is not in L for the supplied bases")

    beta = modular_product(N, normalized_roots, z)
    if beta * beta % N != 1:
        raise ArithmeticError("verified square-base relation did not yield a square root of unity")
    gcd_minus = gcd(beta - 1, N)
    gcd_plus = gcd(beta + 1, N)
    if beta in (1, N - 1):
        return RelationClassification(
            relation=z,
            root_product=beta,
            relation_class="L0",
            gcd_minus=gcd_minus,
            gcd_plus=gcd_plus,
            factor_pair=None,
        )

    factor = next((g for g in (gcd_minus, gcd_plus) if 1 < g < N), None)
    if factor is None:
        raise ArithmeticError("a nontrivial square root of unity yielded no nontrivial GCD")
    factor_pair = tuple(sorted((factor, N // factor)))
    return RelationClassification(
        relation=z,
        root_product=beta,
        relation_class="L_minus_L0",
        gcd_minus=gcd_minus,
        gcd_plus=gcd_plus,
        factor_pair=factor_pair,
    )


def _canonical_sign(vector: tuple[int, ...]) -> tuple[tuple[int, ...], int]:
    first = next(value for value in vector if value)
    sign = 1 if first > 0 else -1
    return tuple(sign * value for value in vector), sign


def _extract_candidates(
    N: int,
    bases: tuple[int, ...],
    stored_roots: tuple[int, ...],
    embedding: AugmentedLattice,
    reduction: LLLReduction,
    row_indices: Sequence[int],
) -> tuple[tuple[LatticeRelationCandidate, ...], int, int]:
    selected_indices = tuple(_as_integer(value, "row index") for value in row_indices)
    if len(set(selected_indices)) != len(selected_indices):
        raise ValueError("row indices must be unique")
    if any(index_value < 0 or index_value >= len(reduction.reduced_rows) for index_value in selected_indices):
        raise IndexError("row index is outside the reduced basis")
    ordered_rows = sorted(
        (
            (
                row_index,
                (
                    reduction.reduced_rows[row_index],
                    reduction.transform_rows[row_index],
                ),
            )
            for row_index in selected_indices
        ),
        key=lambda item: (sum(value * value for value in item[1][0]), item[0]),
    )
    candidates: list[LatticeRelationCandidate] = []
    seen: set[tuple[int, ...]] = set()
    zero_projection_rows = 0
    rejected_nonrelation_rows = 0

    for source_row, (reduced_row, transform_row) in ordered_rows:
        relation = tuple(transform_row[i] for i in range(embedding.dimension))
        expected_prefix = tuple(
            embedding.clearing_factor * value for value in relation
        )
        if reduced_row[: embedding.dimension] != expected_prefix:
            raise ArithmeticError("LLL transform and cleared relation prefix disagree")
        if not any(relation):
            zero_projection_rows += 1
            continue
        relation, sign = _canonical_sign(relation)
        cleared_row = tuple(sign * value for value in reduced_row)
        if relation in seen:
            continue
        if modular_product(N, bases, relation) != 1:
            rejected_nonrelation_rows += 1
            continue
        seen.add(relation)
        classification = _classify_relation_with_stored_roots(
            N, bases, stored_roots, relation
        )
        squared_norm = sum(value * value for value in cleared_row)
        candidates.append(
            LatticeRelationCandidate(
                relation=relation,
                source_row=source_row,
                cleared_embedding_vector=cleared_row,
                cleared_squared_norm=squared_norm,
                embedding_squared_norm=Fraction(
                    squared_norm, embedding.clearing_factor**2
                ),
                root_product=classification.root_product,
                relation_class=classification.relation_class,
                factor_pair=classification.factor_pair,
            )
        )

    return tuple(candidates), zero_projection_rows, rejected_nonrelation_rows


def _regev_lattice_postprocess_explicit(
    N: int,
    bases: Sequence[int],
    stored_roots: Sequence[int],
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    claim_norm_bound: int | Fraction,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
) -> LatticePostprocessingResult:
    """Legacy parallel-argument endpoint; prefer ``regev_lattice_postprocess``."""

    embedding = build_augmented_lattice(
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        require_regev_sample_count=True,
    )
    N, normalized_bases, normalized_roots = _normalize_modular_inputs(
        N, bases, stored_roots, embedding.dimension
    )
    reduction = lll_reduce_augmented_lattice(embedding, delta=lll_delta)
    prefix = claim_5_1_prefix(embedding, reduction, claim_norm_bound)
    prefix_candidates, prefix_zero_rows, prefix_rejected_rows = _extract_candidates(
        N,
        normalized_bases,
        normalized_roots,
        embedding,
        reduction,
        range(prefix.prefix_length),
    )
    all_candidates, all_zero_rows, all_rejected_rows = _extract_candidates(
        N,
        normalized_bases,
        normalized_roots,
        embedding,
        reduction,
        range(prefix.lattice_dimension),
    )
    factor_pair = next(
        (
            candidate.factor_pair
            for candidate in prefix_candidates
            if candidate.factor_pair
        ),
        None,
    )
    diagnostic_factor_pair = next(
        (
            candidate.factor_pair
            for candidate in all_candidates
            if candidate.factor_pair
        ),
        None,
    )
    return LatticePostprocessingResult(
        embedding=embedding,
        reduction=reduction,
        claim_prefix=prefix,
        claim_prefix_candidates=prefix_candidates,
        all_basis_diagnostic_candidates=all_candidates,
        factor_pair=factor_pair,
        all_basis_diagnostic_factor_pair=diagnostic_factor_pair,
        claim_prefix_zero_projection_rows=prefix_zero_rows,
        claim_prefix_rejected_nonrelation_rows=prefix_rejected_rows,
        all_basis_zero_projection_rows=all_zero_rows,
        all_basis_rejected_nonrelation_rows=all_rejected_rows,
    )


def regev_lattice_postprocess(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    claim_norm_bound: int | Fraction,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
) -> LatticePostprocessingResult:
    """Primary rooted-family samples -> Claim 5.1 prefix -> factor endpoint.

    Keeping ``N``, roots, and squared bases inside one immutable
    ``RootedBaseFamily`` prevents an experiment from accidentally classifying
    samples with roots different from those used to construct its circuit
    bases.  ``factor_pair`` is derived only from Claim 5.1's prefix;
    ``all_basis_diagnostic_factor_pair`` is explicitly non-primary.
    """

    if not isinstance(family, RootedBaseFamily):
        raise TypeError("lattice post-processing requires a RootedBaseFamily")
    return _regev_lattice_postprocess_explicit(
        N=family.N,
        bases=family.bases,
        stored_roots=family.roots,
        samples=samples,
        modulus=modulus,
        claim_norm_bound=claim_norm_bound,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
