"""Cost-audited recovery interventions around the augmented Regev lattice.

This module deliberately separates three concerns:

* :mod:`regev_research.lattice` constructs and LLL-reduces the exact augmented
  lattice;
* this module enumerates bounded combinations of reduced rows and verifies
  their projected relations against an immutable :class:`RootedBaseFamily`;
* an optional quotient/deflation module may supply a relation lift or a
  canonical quotient key through the hooks below.  No import of such a module
  is required here.

Intervention A orders the same finite coefficient search by the exact norm of
the resulting cleared embedding vector.  Intervention B de-duplicates by exact
Hermite-reduced cosets of the unsaturated integer lattice generated by verified
``L0`` rows.  Intervention C adaptively suppresses
the exact integer lattice generated by relations already verified to be in
``L0``.  C never suppresses a vector merely because it lies in the *rational*
span of known ``L0`` directions: doing so could erase a nontrivial torsion
coset.  These are bounded experimental searches, not a proof of exhaustive
SVP/CVP recovery.

The BKZ comparison uses ``fpylll`` only when a transformation matrix can be
obtained and verified.  Otherwise its result is labelled, in both strategy and
backend fields, as a deterministic strong-LLL plus bounded block-combination
surrogate and is never called BKZ.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from fractions import Fraction
from itertools import product
from operator import index
from time import perf_counter
from typing import TYPE_CHECKING, Callable, Hashable, Iterable, Sequence

import numpy as np

from .core import RootedBaseFamily, classify_square_relation, modular_product
from .lattice import (
    AugmentedLattice,
    LLLReduction,
    build_augmented_lattice,
    lll_reduce_augmented_lattice,
)

if TYPE_CHECKING:
    from .quotient import IntegerQuotient


RelationLift = Callable[[tuple[int, ...]], Sequence[int]]
QuotientKey = Callable[
    [tuple[int, ...], tuple[tuple[int, ...], ...]], Hashable
]


@dataclass(frozen=True)
class RecoveryBudget:
    """Common bounded-search budget used for matched comparisons."""

    enumeration_rows: int = 6
    coefficient_bound: int = 2
    max_support: int | None = None
    max_nodes: int = 20_000
    max_materialized_nodes: int = 1_000_000

    def __post_init__(self) -> None:
        if self.enumeration_rows <= 0:
            raise ValueError("enumeration_rows must be positive")
        if self.coefficient_bound <= 0:
            raise ValueError("coefficient_bound must be positive")
        if self.max_support is not None and self.max_support <= 0:
            raise ValueError("max_support must be positive when supplied")
        if self.max_nodes <= 0:
            raise ValueError("max_nodes must be positive")
        if self.max_materialized_nodes <= 0:
            raise ValueError("max_materialized_nodes must be positive")


@dataclass(frozen=True)
class RecoveryResources:
    """Measured counters and a deterministic memory-footprint estimate."""

    nodes_generated: int
    nodes_visited: int
    duplicate_relation_nodes: int
    zero_projection_nodes: int
    modular_relation_checks: int
    verified_relations: int
    root_classifications: int
    suppressed_l0_nodes: int
    l0_generators_discovered: int
    reductions: int
    reduction_backend: str
    runtime_seconds: float
    peak_memory_estimate_bytes: int
    memory_estimate_method: str
    input_samples: int
    extra_samples_used: int
    enumeration_rows: int
    coefficient_bound: int
    max_support: int
    node_budget: int
    node_budget_exhausted: bool


@dataclass(frozen=True)
class RecoveryCandidate:
    """One exactly verified relation found by reduced-row enumeration."""

    relation: tuple[int, ...]
    projected_relation: tuple[int, ...]
    coefficients: tuple[int, ...]
    cleared_embedding_squared_norm: int
    relation_class: str
    root_product: int | None
    factor_pair: tuple[int, int] | None
    discovery_node: int


@dataclass(frozen=True)
class RecoveryResult:
    """A recovery result with its exact embedding, reduction, and costs."""

    strategy: str
    embedding: AugmentedLattice
    reduction: LLLReduction
    candidates: tuple[RecoveryCandidate, ...]
    factor_pair: tuple[int, int] | None
    discovered_l0_basis: tuple[tuple[int, ...], ...]
    resources: RecoveryResources
    selected_extra_sample_indices: tuple[int, ...] = ()
    interpretation: str = ""
    quotient_invariants: "QuotientInvariants | None" = None


@dataclass(frozen=True)
class MatchedCostRecoveryComparison:
    """Interventions and baselines run under one coefficient-node budget."""

    budget: RecoveryBudget
    matching_rule: str
    results: tuple[RecoveryResult, ...]


@dataclass(frozen=True)
class QuotientInvariants:
    """Exact invariants of ``Z^d/U`` without saturating the supplied ``U``."""

    input_directions: tuple[tuple[int, ...], ...]
    hnf_basis: tuple[tuple[int, ...], ...]
    rank: int
    free_rank: int
    smith_diagonal: tuple[int, ...]
    torsion_invariant_factors: tuple[int, ...]
    torsion_order: int
    torsion_exponent: int
    saturation_index_reported_not_applied: int
    canonicalization: str = "exact row-HNF reduction modulo unsaturated integer U"


@dataclass(frozen=True)
class ExactUnsaturatedQuotientKey:
    """Hashable-key adapter backed by one exact :class:`IntegerQuotient`."""

    quotient: "IntegerQuotient"
    invariants: QuotientInvariants

    def __call__(
        self,
        relation: tuple[int, ...],
        _dynamically_known_l0: tuple[tuple[int, ...], ...],
    ) -> Hashable:
        # The helper is intentionally frozen to the verified U used to build
        # it.  LDAR rebuilds it after U changes; it never silently changes the
        # equivalence relation halfway through one de-duplication pass.
        return self.quotient.reduce(relation)


@dataclass(frozen=True)
class LDARStage:
    """One reduction/enumeration pass at a fixed accumulated sample count."""

    stage_index: int
    sample_count: int
    deflation_round_at_sample_count: int
    newly_acquired_sample_indices: tuple[int, ...]
    quotient_before: QuotientInvariants
    quotient_after: QuotientInvariants
    u_changed: bool
    deflation_round_limit_reached: bool
    newly_verified_l0_directions: tuple[tuple[int, ...], ...]
    factor_pair: tuple[int, int] | None
    candidate_relations: tuple[tuple[int, ...], ...]
    candidate_classes: tuple[str, ...]
    resources: RecoveryResources


@dataclass(frozen=True)
class LDARTotalResources:
    stages: int
    nodes_generated: int
    nodes_visited: int
    modular_relation_checks: int
    root_classifications: int
    suppressed_l0_nodes: int
    reductions: int
    runtime_seconds: float
    peak_memory_estimate_bytes: int


@dataclass(frozen=True)
class LDARResult:
    """Sequential lattice/deflation/adaptive-resampling recovery transcript."""

    method: str
    root_blind: bool
    initial_sample_count: int
    final_sample_count: int
    frozen_max_sample_count: int
    samples_per_acquisition: int
    selected_fresh_sample_indices: tuple[int, ...]
    stages: tuple[LDARStage, ...]
    final_u: tuple[tuple[int, ...], ...]
    final_quotient: QuotientInvariants
    factor_pair: tuple[int, int] | None
    termination_reason: str
    total_resources: LDARTotalResources


@dataclass(frozen=True)
class DeletedAugmentedBasisRow:
    """One actual free-basis row removed to choose a quotient section."""

    deletion_index: int
    row_position_before_deletion: int
    cleared_augmented_row: tuple[int, ...]
    original_embedding_coefficients: tuple[int, ...]
    projected_l0_relation: tuple[int, ...]
    root_product: int
    cleared_squared_norm: int
    primitive_in_current_free_row_basis: bool


@dataclass(frozen=True)
class AugmentedDeflationResources:
    projected_rows_checked: int
    modular_relation_checks: int
    root_classifications: int
    reductions: int
    deleted_rows: int
    runtime_seconds: float
    peak_memory_estimate_bytes: int
    reduction_backends: tuple[str, ...]


@dataclass(frozen=True)
class AugmentedBasisDeflationResult:
    """Transcript of exact basis-row deletion and rectangular re-LLL."""

    strategy: str
    embedding: AugmentedLattice
    deleted_rows: tuple[DeletedAugmentedBasisRow, ...]
    relation_u: tuple[tuple[int, ...], ...]
    quotient_invariants: QuotientInvariants
    factor_relation: tuple[int, ...] | None
    factor_pair: tuple[int, int] | None
    final_reduced_rows: tuple[tuple[int, ...], ...]
    final_transform_rows: tuple[tuple[int, ...], ...]
    termination_reason: str
    resources: AugmentedDeflationResources
    interpretation: str


def _as_int(value: object, name: str) -> int:
    if isinstance(value, bool):
        raise TypeError(f"{name} must be an integer, not bool")
    try:
        return int(index(value))
    except TypeError as exc:
        raise TypeError(f"{name} must be an integer") from exc


def _canonical_sign(vector: Sequence[int]) -> tuple[tuple[int, ...], int]:
    normalized = tuple(int(value) for value in vector)
    if not any(normalized):
        return normalized, 1
    sign = 1 if next(value for value in normalized if value) > 0 else -1
    return tuple(sign * value for value in normalized), sign


def _factor_pair(N: int, factor: int | None) -> tuple[int, int] | None:
    if factor is None:
        return None
    if not 1 < factor < N or N % factor:
        raise ArithmeticError("relation classifier returned an invalid factor")
    return tuple(sorted((factor, N // factor)))


def _quotient_invariants(quotient: "IntegerQuotient") -> QuotientInvariants:
    return QuotientInvariants(
        input_directions=quotient.input_directions,
        hnf_basis=quotient.hnf_basis,
        rank=quotient.rank,
        free_rank=quotient.free_rank,
        smith_diagonal=quotient.smith_diagonal,
        torsion_invariant_factors=quotient.torsion_invariant_factors,
        torsion_order=quotient.torsion_order,
        torsion_exponent=quotient.torsion_exponent,
        saturation_index_reported_not_applied=quotient.saturation_index,
    )


def _zero_u_invariants(dimension: int) -> QuotientInvariants:
    return QuotientInvariants(
        input_directions=(),
        hnf_basis=(),
        rank=0,
        free_rank=dimension,
        smith_diagonal=(),
        torsion_invariant_factors=(),
        torsion_order=1,
        torsion_exponent=1,
        saturation_index_reported_not_applied=1,
    )


def _root_blind_identity_key(
    relation: tuple[int, ...],
    _known_l0: tuple[tuple[int, ...], ...],
) -> Hashable:
    """Zero-U key that deliberately reads no root metadata."""

    return relation


def build_exact_unsaturated_quotient_key(
    family: RootedBaseFamily,
    verified_l0_directions: Sequence[Sequence[int]],
) -> ExactUnsaturatedQuotientKey:
    """Build an exact canonical key modulo the *integer* lattice ``U``.

    Every nonzero row is verified by :func:`build_l0_quotient`.  An empty
    direction list produces the zero sublattice, so the key is simply the
    canonical ambient integer vector.  Smith torsion and the saturation index
    are reported for diagnosis only: neither is used to enlarge ``U``.
    """

    if not isinstance(family, RootedBaseFamily):
        raise TypeError("quotient-key construction requires a RootedBaseFamily")
    # Local import keeps this recovery module usable while quotient.py evolves
    # and avoids any import cycle through optional experiment orchestration.
    from .quotient import build_l0_quotient

    quotient = build_l0_quotient(family, verified_l0_directions)
    return ExactUnsaturatedQuotientKey(
        quotient=quotient,
        invariants=_quotient_invariants(quotient),
    )


def _integer_bytes(value: int) -> int:
    # Approximate a Python integer by its object header plus magnitude bytes.
    return 28 + max(1, (abs(int(value)).bit_length() + 7) // 8)


def _matrix_memory_estimate(rows: Sequence[Sequence[int]]) -> int:
    return 64 + sum(
        64 + 8 * len(row) + sum(_integer_bytes(value) for value in row)
        for row in rows
    )


def _state_memory_estimate(
    embedding: AugmentedLattice,
    reduction: LLLReduction,
    *,
    materialized_coefficients: int,
    coefficient_width: int,
    seen_relations: int,
    relation_dimension: int,
    candidate_count: int,
    l0_basis: Sequence[Sequence[int]],
) -> int:
    matrices = (
        _matrix_memory_estimate(embedding.integer_row_basis)
        + _matrix_memory_estimate(reduction.reduced_rows)
        + _matrix_memory_estimate(reduction.transform_rows)
        + _matrix_memory_estimate(l0_basis)
    )
    coefficient_storage = materialized_coefficients * (
        64 + 8 * coefficient_width + 28 * coefficient_width
    )
    relation_storage = (seen_relations + candidate_count) * (
        96 + 8 * relation_dimension + 28 * relation_dimension
    )
    return matrices + coefficient_storage + relation_storage


class _ExactGeneratedL0Lattice:
    """Exact integer span of verified L0 vectors, maintained in column HNF."""

    def __init__(self, dimension: int) -> None:
        self.dimension = dimension
        self._basis: tuple[tuple[int, ...], ...] = ()

    @property
    def basis(self) -> tuple[tuple[int, ...], ...]:
        return self._basis

    def contains(self, vector: Sequence[int]) -> bool:
        z = tuple(int(value) for value in vector)
        if len(z) != self.dimension:
            raise ValueError("L0 membership vector has the wrong dimension")
        if not self._basis:
            return not any(z)
        try:
            from sympy import Matrix
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError("SymPy is required for exact L0 suppression") from exc
        columns = Matrix(self._basis).T
        try:
            solution, parameters = columns.gauss_jordan_solve(Matrix(z))
        except ValueError:
            return False
        if parameters.rows:
            raise ArithmeticError("HNF basis unexpectedly had dependent columns")
        return all(value.q == 1 for value in solution)

    def add(self, vector: Sequence[int]) -> bool:
        z, _ = _canonical_sign(vector)
        if len(z) != self.dimension or not any(z):
            raise ValueError("an L0 generator must be a nonzero vector of dimension d")
        if self.contains(z):
            return False
        try:
            from sympy import Matrix
            from sympy.matrices.normalforms import hermite_normal_form
        except ImportError as exc:  # pragma: no cover
            raise RuntimeError("SymPy is required for exact L0 suppression") from exc
        generators = [*self._basis, z]
        hnf = hermite_normal_form(Matrix(generators).T)
        basis = tuple(
            tuple(int(hnf[row, column]) for row in range(self.dimension))
            for column in range(hnf.cols)
        )
        if any(not any(row) for row in basis):
            raise ArithmeticError("HNF returned a zero L0 generator")
        self._basis = basis
        return True


def exact_generated_l0_membership(
    generators: Sequence[Sequence[int]], vector: Sequence[int]
) -> bool:
    """Public audit helper for exact *integer*, not rational-span, membership."""

    z = tuple(int(value) for value in vector)
    lattice = _ExactGeneratedL0Lattice(len(z))
    for generator in generators:
        lattice.add(generator)
    return lattice.contains(z)


def _coefficient_vectors(
    width: int, bound: int, max_support: int
) -> Iterable[tuple[int, ...]]:
    """Yield one sign-canonical representative in expanding L-infinity shells."""

    for radius in range(1, bound + 1):
        for coefficients in product(range(-radius, radius + 1), repeat=width):
            if max(abs(value) for value in coefficients) != radius:
                continue
            if sum(value != 0 for value in coefficients) > max_support:
                continue
            first = next((value for value in coefficients if value), 0)
            if first > 0:
                yield tuple(int(value) for value in coefficients)


def _combine_rows(
    coefficients: Sequence[int], rows: Sequence[Sequence[int]]
) -> tuple[int, ...]:
    return tuple(
        sum(coefficient * rows[i][j] for i, coefficient in enumerate(coefficients))
        for j in range(len(rows[0]))
    )


def _ordered_coefficient_nodes(
    rows: Sequence[Sequence[int]],
    budget: RecoveryBudget,
    ordering: str,
) -> tuple[Iterable[tuple[int, ...]], int, int]:
    width = len(rows)
    max_support = min(width, budget.max_support or width)
    stream = _coefficient_vectors(width, budget.coefficient_bound, max_support)
    if ordering == "shell_lexicographic":
        return stream, 0, max_support
    if ordering != "exact_embedding_norm":
        raise ValueError("ordering must be shell_lexicographic or exact_embedding_norm")

    nodes = []
    for coefficients in stream:
        if len(nodes) >= budget.max_materialized_nodes:
            raise ValueError(
                "norm ordering would exceed max_materialized_nodes; reduce rows, "
                "coefficient_bound, or max_support"
            )
        nodes.append(coefficients)
    nodes.sort(key=lambda coefficients: (
        sum(value * value for value in _combine_rows(coefficients, rows)),
        max(abs(value) for value in coefficients),
        coefficients,
    ))
    return nodes, len(nodes), max_support


def enumerate_reduced_basis_combinations(
    family: RootedBaseFamily,
    embedding: AugmentedLattice,
    reduction: LLLReduction,
    *,
    budget: RecoveryBudget = RecoveryBudget(),
    strategy: str = "A_short_combination_enumeration",
    ordering: str = "exact_embedding_norm",
    adaptive_l0_suppression: bool = False,
    seed_l0_directions: Sequence[Sequence[int]] = (),
    relation_lift: RelationLift | None = None,
    quotient_key: QuotientKey | None = None,
    root_blind: bool = False,
    reductions: int = 0,
    extra_samples_used: int = 0,
    stop_on_factor: bool = False,
    max_stored_candidates: int = 512,
    started_at: float | None = None,
) -> RecoveryResult:
    """Enumerate bounded combinations of an already reduced augmented basis.

    ``relation_lift`` maps the raw first-``d`` transform coefficients to an
    original relation.  It is the composition seam for exact quotient or
    deflation code.  ``quotient_key`` may provide a canonical de-duplication
    key using the current exact HNF basis of discovered ``L0`` directions.
    Both hooks are optional, and neither is trusted: every lifted vector is
    re-verified in ``L``.  Unless ``root_blind=True``, it is then classified
    with the roots stored in ``family``.  The root-blind ablation performs no
    root product, GCD, L0 classification, or suppression.
    """

    if not isinstance(family, RootedBaseFamily):
        raise TypeError("recovery requires an immutable RootedBaseFamily")
    if embedding.dimension != len(family.pairs):
        raise ValueError("embedding dimension does not match the rooted family")
    lattice_dimension = embedding.dimension + embedding.sample_count
    if len(reduction.reduced_rows) != lattice_dimension:
        raise ValueError("reduction row count does not match the embedding")
    if len(reduction.transform_rows) != lattice_dimension:
        raise ValueError("reduction transform count does not match the embedding")
    if max_stored_candidates <= 0:
        raise ValueError("max_stored_candidates must be positive")
    if root_blind and adaptive_l0_suppression:
        raise ValueError("root_blind recovery cannot suppress or classify L0")
    if root_blind and seed_l0_directions:
        raise ValueError("root_blind recovery cannot accept verified L0 directions")

    start = perf_counter() if started_at is None else started_at
    row_count = min(budget.enumeration_rows, lattice_dimension)
    selected_indices = sorted(
        range(lattice_dimension),
        key=lambda i: (
            sum(value * value for value in reduction.reduced_rows[i]),
            i,
        ),
    )[:row_count]
    reduced_rows = tuple(reduction.reduced_rows[i] for i in selected_indices)
    transform_rows = tuple(reduction.transform_rows[i] for i in selected_indices)
    coefficient_nodes, materialized_count, max_support = _ordered_coefficient_nodes(
        reduced_rows, budget, ordering
    )

    l0_lattice = _ExactGeneratedL0Lattice(embedding.dimension)
    for i, direction in enumerate(seed_l0_directions):
        relation, _ = _canonical_sign(direction)
        if len(relation) != embedding.dimension or not any(relation):
            raise ValueError(f"seed_l0_directions[{i}] has invalid dimension or is zero")
        classification = classify_square_relation(family, relation)
        if classification["class"] != "L0":
            raise ValueError(f"seed_l0_directions[{i}] is not a verified L0 relation")
        l0_lattice.add(relation)

    candidates: list[RecoveryCandidate] = []
    seen_keys: set[Hashable] = set()
    nodes_generated = materialized_count
    nodes_visited = 0
    duplicates = 0
    zero_projections = 0
    modular_checks = 0
    verified = 0
    classifications = 0
    suppressed = 0
    discovered = len(l0_lattice.basis)
    factor_pair = None
    exhausted = False

    for coefficients in coefficient_nodes:
        if materialized_count == 0:
            nodes_generated += 1
        if nodes_visited >= budget.max_nodes:
            exhausted = True
            break
        nodes_visited += 1
        cleared_vector = _combine_rows(coefficients, reduced_rows)
        projected = tuple(
            sum(
                coefficient * transform_rows[i][coordinate]
                for i, coefficient in enumerate(coefficients)
            )
            for coordinate in range(embedding.dimension)
        )
        expected_prefix = tuple(
            embedding.clearing_factor * value for value in projected
        )
        if cleared_vector[: embedding.dimension] != expected_prefix:
            raise ArithmeticError("reduced rows and transform disagree on relation projection")
        if not any(projected):
            zero_projections += 1
            continue
        projected, sign = _canonical_sign(projected)
        coefficients = tuple(sign * value for value in coefficients)
        cleared_vector = tuple(sign * value for value in cleared_vector)

        if relation_lift is None:
            relation = projected
        else:
            relation = tuple(_as_int(value, "lifted relation coordinate") for value in relation_lift(projected))
            if len(relation) != embedding.dimension:
                raise ValueError("relation_lift returned the wrong dimension")
            relation, lift_sign = _canonical_sign(relation)
            if not any(relation):
                zero_projections += 1
                continue
            if lift_sign < 0:
                coefficients = tuple(-value for value in coefficients)
                cleared_vector = tuple(-value for value in cleared_vector)

        known_l0 = l0_lattice.basis
        key = (
            quotient_key(relation, known_l0)
            if quotient_key is not None
            else relation
        )
        try:
            duplicate = key in seen_keys
        except TypeError as exc:
            raise TypeError("quotient_key must return a hashable value") from exc
        if duplicate:
            duplicates += 1
            continue
        seen_keys.add(key)

        if adaptive_l0_suppression and l0_lattice.contains(relation):
            suppressed += 1
            continue
        modular_checks += 1
        if modular_product(family.N, family.bases, relation) != 1:
            continue
        verified += 1
        if root_blind:
            relation_class = "L_unclassified_root_blind"
            root_product = None
            relation_factor_pair = None
        else:
            classification = classify_square_relation(family, relation)
            classifications += 1
            relation_class = str(classification["class"])
            root_product = int(classification["root_product"])
            relation_factor_pair = _factor_pair(family.N, classification["factor"])
        if len(candidates) < max_stored_candidates:
            candidates.append(
                RecoveryCandidate(
                    relation=relation,
                    projected_relation=projected,
                    coefficients=coefficients,
                    cleared_embedding_squared_norm=sum(
                        value * value for value in cleared_vector
                    ),
                    relation_class=relation_class,
                    root_product=root_product,
                    factor_pair=relation_factor_pair,
                    discovery_node=nodes_visited,
                )
            )
        if relation_class == "L0" and adaptive_l0_suppression:
            if l0_lattice.add(relation):
                discovered += 1
        if relation_factor_pair is not None and factor_pair is None:
            factor_pair = relation_factor_pair
            if stop_on_factor:
                break

    memory_estimate = _state_memory_estimate(
        embedding,
        reduction,
        materialized_coefficients=materialized_count,
        coefficient_width=row_count,
        seen_relations=len(seen_keys),
        relation_dimension=embedding.dimension,
        candidate_count=len(candidates),
        l0_basis=l0_lattice.basis,
    )
    resources = RecoveryResources(
        nodes_generated=nodes_generated,
        nodes_visited=nodes_visited,
        duplicate_relation_nodes=duplicates,
        zero_projection_nodes=zero_projections,
        modular_relation_checks=modular_checks,
        verified_relations=verified,
        root_classifications=classifications,
        suppressed_l0_nodes=suppressed,
        l0_generators_discovered=discovered,
        reductions=reductions,
        reduction_backend=reduction.backend,
        runtime_seconds=perf_counter() - start,
        peak_memory_estimate_bytes=memory_estimate,
        memory_estimate_method=(
            "deterministic structural estimate: Python-int magnitude plus tuple/"
            "matrix/coefficient/relation storage; not process RSS"
        ),
        input_samples=embedding.sample_count - extra_samples_used,
        extra_samples_used=extra_samples_used,
        enumeration_rows=row_count,
        coefficient_bound=budget.coefficient_bound,
        max_support=max_support,
        node_budget=budget.max_nodes,
        node_budget_exhausted=exhausted,
    )
    interpretation = (
        "Exact bounded coefficient search over reduced rows; absence of a factor "
        "does not establish absence of L\\L0 vectors."
    )
    if adaptive_l0_suppression:
        interpretation += (
            " Suppression applies only to the exact integer span of verified L0 "
            "directions, never their rational span."
        )
    if root_blind:
        interpretation += (
            " Root-blind ablation: candidates are checked only for L membership; "
            "no stored root is evaluated and no L0/factor label is produced."
        )
    return RecoveryResult(
        strategy=strategy,
        embedding=embedding,
        reduction=reduction,
        candidates=tuple(candidates),
        factor_pair=factor_pair,
        discovered_l0_basis=l0_lattice.basis,
        resources=resources,
        interpretation=interpretation,
    )


def _build_and_reduce(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None,
    noise_bound: int | Fraction | None,
    lll_delta: Fraction,
) -> tuple[AugmentedLattice, LLLReduction, float]:
    start = perf_counter()
    embedding = build_augmented_lattice(
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        require_regev_sample_count=True,
    )
    if embedding.dimension != len(family.pairs):
        raise ValueError("sample dimension does not match the rooted family")
    reduction = lll_reduce_augmented_lattice(embedding, delta=lll_delta)
    return embedding, reduction, start


def short_combination_recovery(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
    relation_lift: RelationLift | None = None,
    quotient_key: QuotientKey | None = None,
) -> RecoveryResult:
    """Intervention A: exact-norm-prioritized short LLL-row combinations."""

    embedding, reduction, start = _build_and_reduce(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    return enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=budget,
        strategy="A_short_combination_enumeration",
        ordering="exact_embedding_norm",
        relation_lift=relation_lift,
        quotient_key=quotient_key,
        reductions=1,
        started_at=start,
    )


def adaptive_l0_suppression_recovery(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
    seed_l0_directions: Sequence[Sequence[int]] = (),
    relation_lift: RelationLift | None = None,
    quotient_key: QuotientKey | None = None,
) -> RecoveryResult:
    """Intervention C: continue search while exactly suppressing known L0 span."""

    embedding, reduction, start = _build_and_reduce(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    return enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=budget,
        strategy="C_adaptive_exact_L0_suppression",
        ordering="shell_lexicographic",
        adaptive_l0_suppression=True,
        seed_l0_directions=seed_l0_directions,
        relation_lift=relation_lift,
        quotient_key=quotient_key,
        reductions=1,
        started_at=start,
    )


def exact_quotient_deduplicated_recovery(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    verified_l0_directions: Sequence[Sequence[int]] = (),
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
    ordering: str = "exact_embedding_norm",
    relation_lift: RelationLift | None = None,
    root_blind: bool = False,
) -> RecoveryResult:
    """Intervention B: de-duplicate candidates by their exact coset modulo ``U``.

    ``verified_l0_directions`` generates the integer row lattice ``U`` exactly.
    Its Hermite basis is not saturated or rationally projected.  In root-blind
    mode only ``U=0`` is permitted, since that ablation cannot verify an L0
    direction.
    """

    if root_blind and verified_l0_directions:
        raise ValueError("root_blind quotient recovery requires the zero U lattice")
    if root_blind:
        quotient_helper = None
        quotient_key_function: QuotientKey = _root_blind_identity_key
        quotient_invariants = _zero_u_invariants(len(family.pairs))
    else:
        quotient_helper = build_exact_unsaturated_quotient_key(
            family, verified_l0_directions
        )
        quotient_key_function = quotient_helper
        quotient_invariants = quotient_helper.invariants
    embedding, reduction, start = _build_and_reduce(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    result = enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=budget,
        strategy=(
            "B_exact_unsaturated_quotient_deduplication_root_blind"
            if root_blind
            else "B_exact_unsaturated_quotient_deduplication"
        ),
        ordering=ordering,
        relation_lift=relation_lift,
        quotient_key=quotient_key_function,
        root_blind=root_blind,
        reductions=1,
        started_at=start,
    )
    return replace(
        result,
        quotient_invariants=quotient_invariants,
        interpretation=(
            f"{result.interpretation} Candidate keys are exact Hermite-reduced "
            "cosets modulo the supplied unsaturated integer U; Smith invariants "
            "are reported but never used to enlarge U."
        ),
    )


def _rectangular_exact_row_lll(
    rows: Sequence[Sequence[int]],
    original_transform_rows: Sequence[Sequence[int]],
    original_basis: Sequence[Sequence[int]],
    *,
    delta: Fraction,
) -> tuple[tuple[tuple[int, ...], ...], tuple[tuple[int, ...], ...], str]:
    """LLL rows and compose its square row transform back to ``original_basis``."""

    try:
        from sympy import Matrix, Rational
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("SymPy is required for exact rectangular row LLL") from exc
    row_matrix = Matrix(rows)
    transform_matrix = Matrix(original_transform_rows)
    if row_matrix.rows > row_matrix.cols:
        raise ValueError("row LLL requires no more rows than ambient columns")
    if transform_matrix.rows != row_matrix.rows:
        raise ValueError("row and composed-transform counts disagree")
    try:
        reduced, local_transform = row_matrix.lll_transform(
            delta=Rational(delta.numerator, delta.denominator)
        )
    except Exception as exc:  # SymPy exposes backend-specific rectangular errors.
        raise RuntimeError(
            "exact rectangular SymPy row-LLL is unavailable for this basis; "
            "no projection or fake deflation was substituted"
        ) from exc
    composed = local_transform * transform_matrix
    original = Matrix(original_basis)
    if composed * original != reduced:
        raise ArithmeticError("rectangular LLL transform did not compose to the original basis")
    return (
        tuple(tuple(int(value) for value in row) for row in reduced.tolist()),
        tuple(tuple(int(value) for value in row) for row in composed.tolist()),
        "sympy.Matrix.lll_transform rectangular exact row basis",
    )


def exact_augmented_basis_deflation_from_reduction(
    family: RootedBaseFamily,
    embedding: AugmentedLattice,
    reduction: LLLReduction,
    *,
    lll_delta: Fraction = Fraction(3, 4),
    max_deletions: int | None = None,
    initial_reductions: int = 0,
    started_at: float | None = None,
) -> AugmentedBasisDeflationResult:
    """Delete verified-L0 *basis rows* and re-LLL the exact chosen section.

    A deleted row is an actual element of the current free row basis, hence a
    primitive generator of that free module.  Deleting it realizes the chosen
    section spanned by the remaining basis rows.  The remaining rectangular
    integer basis is row-LLL reduced, and every local unimodular transform is
    composed back to the original augmented basis.  No row is divided,
    projected, saturated, or removed merely through rational-span membership.
    """

    if not isinstance(family, RootedBaseFamily):
        raise TypeError("augmented deflation requires a RootedBaseFamily")
    if embedding.dimension != len(family.pairs):
        raise ValueError("embedding dimension does not match the rooted family")
    lattice_dimension = embedding.dimension + embedding.sample_count
    if len(reduction.reduced_rows) != lattice_dimension:
        raise ValueError("initial reduction must be a full augmented row basis")
    if len(reduction.transform_rows) != lattice_dimension:
        raise ValueError("initial transform must be a full augmented row basis")
    if isinstance(lll_delta, bool) or not isinstance(lll_delta, (int, Fraction)):
        raise TypeError("lll_delta must be an int or fractions.Fraction")
    lll_delta = Fraction(lll_delta)
    if not Fraction(1, 4) < lll_delta < 1:
        raise ValueError("lll_delta must lie strictly between 1/4 and 1")
    if max_deletions is None:
        deletion_cap = lattice_dimension
    else:
        deletion_cap = _as_int(max_deletions, "max_deletions")
        if deletion_cap < 0:
            raise ValueError("max_deletions cannot be negative")
    reductions = _as_int(initial_reductions, "initial_reductions")
    if reductions < 0:
        raise ValueError("initial_reductions cannot be negative")

    start = perf_counter() if started_at is None else started_at
    original_basis = embedding.integer_row_basis
    current_rows = tuple(reduction.reduced_rows)
    current_transform = tuple(reduction.transform_rows)
    if any(
        tuple(
            sum(current_transform[i][k] * original_basis[k][j] for k in range(lattice_dimension))
            for j in range(lattice_dimension)
        )
        != current_rows[i]
        for i in range(lattice_dimension)
    ):
        raise ArithmeticError("initial reduction transform does not map the original basis")

    deleted: list[DeletedAugmentedBasisRow] = []
    relation_u = _ExactGeneratedL0Lattice(embedding.dimension)
    projected_checks = 0
    modular_checks = 0
    classifications = 0
    backends = [reduction.backend]
    factor_relation = None
    factor_pair = None
    termination_reason = ""
    peak_memory = (
        _matrix_memory_estimate(original_basis)
        + _matrix_memory_estimate(current_rows)
        + _matrix_memory_estimate(current_transform)
    )

    while current_rows:
        actionable = None
        for row_position in sorted(
            range(len(current_rows)),
            key=lambda i: (sum(value * value for value in current_rows[i]), i),
        ):
            row = current_rows[row_position]
            transform_row = current_transform[row_position]
            projected = tuple(transform_row[i] for i in range(embedding.dimension))
            expected_prefix = tuple(
                embedding.clearing_factor * value for value in projected
            )
            if row[: embedding.dimension] != expected_prefix:
                raise ArithmeticError("row projection disagrees with its original transform")
            if not any(projected):
                continue
            projected_checks += 1
            relation, _ = _canonical_sign(projected)
            modular_checks += 1
            if modular_product(family.N, family.bases, relation) != 1:
                continue
            classification = classify_square_relation(family, relation)
            classifications += 1
            if classification["class"] == "L_minus_L0":
                factor_relation = relation
                factor_pair = _factor_pair(family.N, classification["factor"])
                actionable = ("factor", row_position, relation, classification)
                break
            if classification["class"] == "L0":
                actionable = ("delete", row_position, relation, classification)
                break

        if actionable is None:
            termination_reason = "no_verified_projected_relation_basis_row"
            break
        action, row_position, relation, classification = actionable
        if action == "factor":
            termination_reason = "factor_found_after_exact_augmented_row_deflation"
            break
        if len(deleted) >= deletion_cap:
            termination_reason = "frozen_max_deletions_reached"
            break

        deleted_row = current_rows[row_position]
        deleted_transform = current_transform[row_position]
        # Re-verify immediately at the destructive boundary.
        repeated = classify_square_relation(family, relation)
        classifications += 1
        if repeated["class"] != "L0":
            raise ArithmeticError("attempted to delete a row not verified in L0")
        relation_u.add(relation)
        deleted.append(
            DeletedAugmentedBasisRow(
                deletion_index=len(deleted),
                row_position_before_deletion=row_position,
                cleared_augmented_row=deleted_row,
                original_embedding_coefficients=deleted_transform,
                projected_l0_relation=relation,
                root_product=int(classification["root_product"]),
                cleared_squared_norm=sum(value * value for value in deleted_row),
                primitive_in_current_free_row_basis=True,
            )
        )
        remaining_rows = tuple(
            row for i, row in enumerate(current_rows) if i != row_position
        )
        remaining_transform = tuple(
            row for i, row in enumerate(current_transform) if i != row_position
        )
        if not remaining_rows:
            current_rows = ()
            current_transform = ()
            termination_reason = "all_free_basis_rows_deleted"
            break
        current_rows, current_transform, backend = _rectangular_exact_row_lll(
            remaining_rows,
            remaining_transform,
            original_basis,
            delta=lll_delta,
        )
        reductions += 1
        backends.append(backend)
        peak_memory = max(
            peak_memory,
            _matrix_memory_estimate(original_basis)
            + _matrix_memory_estimate(current_rows)
            + _matrix_memory_estimate(current_transform)
            + _matrix_memory_estimate(relation_u.basis),
        )

    quotient_helper = build_exact_unsaturated_quotient_key(family, relation_u.basis)
    return AugmentedBasisDeflationResult(
        strategy="B_stronger_exact_augmented_free_basis_row_deflation",
        embedding=embedding,
        deleted_rows=tuple(deleted),
        relation_u=relation_u.basis,
        quotient_invariants=quotient_helper.invariants,
        factor_relation=factor_relation,
        factor_pair=factor_pair,
        final_reduced_rows=current_rows,
        final_transform_rows=current_transform,
        termination_reason=termination_reason,
        resources=AugmentedDeflationResources(
            projected_rows_checked=projected_checks,
            modular_relation_checks=modular_checks,
            root_classifications=classifications,
            reductions=reductions,
            deleted_rows=len(deleted),
            runtime_seconds=perf_counter() - start,
            peak_memory_estimate_bytes=peak_memory,
            reduction_backends=tuple(backends),
        ),
        interpretation=(
            "Exact quotient of the current free augmented row module by each "
            "deleted primitive basis generator, represented by the chosen section "
            "spanned by remaining rows; transforms are composed to the original "
            "integer embedding. This is not orthogonal projection, rational-span "
            "deletion, saturation, or a quotient-lattice metric claim."
        ),
    )


def exact_augmented_basis_deflation_recovery(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    max_deletions: int | None = None,
) -> AugmentedBasisDeflationResult:
    """Build, LLL, then run exact augmented free-basis row deflation."""

    embedding, reduction, start = _build_and_reduce(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    return exact_augmented_basis_deflation_from_reduction(
        family,
        embedding,
        reduction,
        lll_delta=lll_delta,
        max_deletions=max_deletions,
        initial_reductions=1,
        started_at=start,
    )


def _normalize_sample_rows_for_ldar(
    rows: Sequence[Sequence[int]],
    *,
    dimension: int,
    modulus: int,
    name: str,
) -> tuple[tuple[int, ...], ...]:
    normalized = tuple(
        tuple(_as_int(value, f"{name}[{i}][{j}]") for j, value in enumerate(row))
        for i, row in enumerate(rows)
    )
    for i, row in enumerate(normalized):
        if len(row) != dimension:
            raise ValueError(f"{name}[{i}] must have dimension {dimension}")
        if any(value < 0 or value >= modulus for value in row):
            raise ValueError(f"{name}[{i}] has a coordinate outside [0, modulus)")
    return normalized


def _aggregate_ldar_resources(stages: Sequence[LDARStage]) -> LDARTotalResources:
    resources = [stage.resources for stage in stages]
    return LDARTotalResources(
        stages=len(stages),
        nodes_generated=sum(row.nodes_generated for row in resources),
        nodes_visited=sum(row.nodes_visited for row in resources),
        modular_relation_checks=sum(row.modular_relation_checks for row in resources),
        root_classifications=sum(row.root_classifications for row in resources),
        suppressed_l0_nodes=sum(row.suppressed_l0_nodes for row in resources),
        reductions=sum(row.reductions for row in resources),
        runtime_seconds=sum(row.runtime_seconds for row in resources),
        peak_memory_estimate_bytes=max(
            (row.peak_memory_estimate_bytes for row in resources), default=0
        ),
    )


def sequential_ldar_recovery(
    family: RootedBaseFamily,
    initial_samples: Sequence[Sequence[int]],
    fresh_sample_pool: Sequence[Sequence[int]],
    modulus: int,
    *,
    frozen_max_sample_count: int,
    fresh_sample_seed: int,
    samples_per_acquisition: int = 1,
    max_deflation_rounds_per_sample_count: int = 8,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
    root_blind: bool = False,
) -> LDARResult:
    """Complete sequential A+B+C recovery with genuine sample acquisition.

    At each accumulated sample count the method:

    1. builds the exact unsaturated quotient ``Z^d/U``;
    2. LLL-reduces and norm-orders bounded row combinations (A);
    3. de-duplicates by the exact quotient key (B);
    4. verifies candidates and adds only stored-root-certified L0 rows to ``U``
       while suppressing their exact integer span (C);
    5. repeats at the same sample count after ``U`` changes, then consumes
       never-before-used rows from the separately supplied fresh pool.

    The method accepts no factors, orders, or relation oracle.  The fresh pool
    is sampled without replacement.  Equal measured values at two distinct
    pool indices are still genuine independent acquisitions; no existing row
    is copied or bootstrapped.

    With ``root_blind=True``, steps 3--4 use only ``U=0`` and candidates are
    checked solely for membership in ``L``.  The ablation never evaluates a
    stored root, classifies L0, suppresses a direction, or extracts a factor.
    """

    if not isinstance(family, RootedBaseFamily):
        raise TypeError("LDAR requires an immutable RootedBaseFamily")
    modulus = _as_int(modulus, "modulus")
    if modulus <= 1:
        raise ValueError("modulus must exceed one")
    dimension = len(family.pairs)
    initial = _normalize_sample_rows_for_ldar(
        initial_samples, dimension=dimension, modulus=modulus, name="initial_samples"
    )
    fresh = _normalize_sample_rows_for_ldar(
        fresh_sample_pool,
        dimension=dimension,
        modulus=modulus,
        name="fresh_sample_pool",
    )
    if len(initial) < dimension + 4:
        raise ValueError("initial_samples must contain at least d + 4 rows")
    frozen_max_sample_count = _as_int(
        frozen_max_sample_count, "frozen_max_sample_count"
    )
    if frozen_max_sample_count < len(initial):
        raise ValueError("frozen_max_sample_count cannot be below the initial count")
    required_fresh = frozen_max_sample_count - len(initial)
    if len(fresh) < required_fresh:
        raise ValueError("fresh_sample_pool is too small for the frozen sample maximum")
    samples_per_acquisition = _as_int(
        samples_per_acquisition, "samples_per_acquisition"
    )
    if samples_per_acquisition <= 0:
        raise ValueError("samples_per_acquisition must be positive")
    max_deflation_rounds_per_sample_count = _as_int(
        max_deflation_rounds_per_sample_count,
        "max_deflation_rounds_per_sample_count",
    )
    if max_deflation_rounds_per_sample_count <= 0:
        raise ValueError("max_deflation_rounds_per_sample_count must be positive")

    rng = np.random.default_rng(_as_int(fresh_sample_seed, "fresh_sample_seed"))
    fresh_order = tuple(int(value) for value in rng.permutation(len(fresh)))
    next_fresh = 0
    selected_fresh: list[int] = []
    accumulated = list(initial)
    pending_new_indices: tuple[int, ...] = ()
    stages: list[LDARStage] = []
    global_u = _ExactGeneratedL0Lattice(dimension)
    factor_pair = None
    termination_reason = ""
    deflation_round = 0

    while True:
        if root_blind:
            quotient_before_helper = None
            quotient_before_invariants = _zero_u_invariants(dimension)
            quotient_key_function: QuotientKey = _root_blind_identity_key
        else:
            quotient_before_helper = build_exact_unsaturated_quotient_key(
                family, global_u.basis
            )
            quotient_before_invariants = quotient_before_helper.invariants
            quotient_key_function = quotient_before_helper
        embedding, reduction, start = _build_and_reduce(
            family,
            accumulated,
            modulus,
            scale=scale,
            noise_bound=noise_bound,
            lll_delta=lll_delta,
        )
        recovery = enumerate_reduced_basis_combinations(
            family,
            embedding,
            reduction,
            budget=budget,
            strategy=(
                "LDAR_root_blind_L_membership_only"
                if root_blind
                else "LDAR_A_norm_B_exact_quotient_C_exact_L0"
            ),
            ordering="exact_embedding_norm",
            adaptive_l0_suppression=not root_blind,
            seed_l0_directions=() if root_blind else global_u.basis,
            quotient_key=quotient_key_function,
            root_blind=root_blind,
            reductions=1,
            started_at=start,
        )

        new_l0: list[tuple[int, ...]] = []
        if not root_blind:
            if quotient_before_helper is None:  # pragma: no cover - type narrowing.
                raise AssertionError("root-aware LDAR lost its quotient helper")
            for candidate in recovery.candidates:
                if candidate.relation_class != "L0":
                    continue
                if not quotient_before_helper.quotient.is_zero(
                    quotient_before_helper.quotient.reduce(candidate.relation)
                ):
                    if global_u.add(candidate.relation):
                        new_l0.append(candidate.relation)
        if root_blind:
            quotient_after_invariants = _zero_u_invariants(dimension)
        else:
            quotient_after_invariants = build_exact_unsaturated_quotient_key(
                family, global_u.basis
            ).invariants
        u_changed = (
            quotient_before_invariants.hnf_basis
            != quotient_after_invariants.hnf_basis
        )
        round_limit_reached = (
            u_changed
            and deflation_round + 1 >= max_deflation_rounds_per_sample_count
        )
        factor_pair = recovery.factor_pair
        stages.append(
            LDARStage(
                stage_index=len(stages),
                sample_count=len(accumulated),
                deflation_round_at_sample_count=deflation_round,
                newly_acquired_sample_indices=pending_new_indices,
                quotient_before=quotient_before_invariants,
                quotient_after=quotient_after_invariants,
                u_changed=u_changed,
                deflation_round_limit_reached=round_limit_reached,
                newly_verified_l0_directions=tuple(new_l0),
                factor_pair=factor_pair,
                candidate_relations=tuple(
                    candidate.relation for candidate in recovery.candidates
                ),
                candidate_classes=tuple(
                    candidate.relation_class for candidate in recovery.candidates
                ),
                resources=recovery.resources,
            )
        )
        pending_new_indices = ()

        if factor_pair is not None:
            termination_reason = "factor_found_from_stored_roots"
            break
        if u_changed and deflation_round + 1 < max_deflation_rounds_per_sample_count:
            deflation_round += 1
            continue

        hit_round_cap = round_limit_reached
        if len(accumulated) >= frozen_max_sample_count:
            termination_reason = (
                "frozen_max_sample_count_reached_after_deflation_round_cap"
                if hit_round_cap
                else "frozen_max_sample_count_reached"
            )
            break

        take = min(
            samples_per_acquisition,
            frozen_max_sample_count - len(accumulated),
        )
        indices = fresh_order[next_fresh : next_fresh + take]
        if len(indices) != take:
            raise ArithmeticError("validated fresh sample pool was unexpectedly exhausted")
        next_fresh += take
        selected_fresh.extend(indices)
        accumulated.extend(fresh[index_value] for index_value in indices)
        pending_new_indices = tuple(indices)
        deflation_round = 0

    final_quotient_invariants = (
        _zero_u_invariants(dimension)
        if root_blind
        else build_exact_unsaturated_quotient_key(family, global_u.basis).invariants
    )
    return LDARResult(
        method=(
            "LDAR_root_blind_ablation"
            if root_blind
            else "LDAR_exact_A_plus_B_plus_C_plus_genuine_new_samples"
        ),
        root_blind=root_blind,
        initial_sample_count=len(initial),
        final_sample_count=len(accumulated),
        frozen_max_sample_count=frozen_max_sample_count,
        samples_per_acquisition=samples_per_acquisition,
        selected_fresh_sample_indices=tuple(selected_fresh),
        stages=tuple(stages),
        final_u=() if root_blind else global_u.basis,
        final_quotient=final_quotient_invariants,
        factor_pair=factor_pair,
        termination_reason=termination_reason,
        total_resources=_aggregate_ldar_resources(stages),
    )


def standard_lll_enumeration_baseline(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
) -> RecoveryResult:
    """Matched baseline: standard LLL and shell/lex bounded enumeration."""

    embedding, reduction, start = _build_and_reduce(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    return enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=budget,
        strategy="baseline_standard_LLL_enumeration",
        ordering="shell_lexicographic",
        reductions=1,
        started_at=start,
    )


def random_extra_samples_baseline(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    extra_sample_pool: Sequence[Sequence[int]],
    modulus: int,
    *,
    extra_count: int,
    seed: int,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    lll_delta: Fraction = Fraction(3, 4),
    budget: RecoveryBudget = RecoveryBudget(),
) -> RecoveryResult:
    """Matched baseline using genuinely additional samples chosen at random.

    The caller must supply an independently generated ``extra_sample_pool``.
    This function never bootstraps existing rows and therefore cannot disguise
    duplicated data as additional information.
    """

    extra_count = _as_int(extra_count, "extra_count")
    if extra_count <= 0 or extra_count > len(extra_sample_pool):
        raise ValueError("extra_count must lie in [1, len(extra_sample_pool)]")
    rng = np.random.default_rng(_as_int(seed, "seed"))
    indices = tuple(
        sorted(int(value) for value in rng.choice(len(extra_sample_pool), extra_count, replace=False))
    )
    combined = [*samples, *(extra_sample_pool[i] for i in indices)]
    embedding, reduction, start = _build_and_reduce(
        family,
        combined,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        lll_delta=lll_delta,
    )
    result = enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=budget,
        strategy="baseline_random_genuine_extra_samples",
        ordering="shell_lexicographic",
        reductions=1,
        extra_samples_used=extra_count,
        started_at=start,
    )
    return replace(result, selected_extra_sample_indices=indices)


def _verified_fpylll_bkz_reduction(
    embedding: AugmentedLattice, block_size: int
) -> LLLReduction | None:
    """Return a transform-verified fpylll BKZ result, or ``None`` if unavailable."""

    try:
        from fpylll import BKZ, IntegerMatrix
    except ImportError:
        return None
    dimension = len(embedding.integer_row_basis)
    basis = IntegerMatrix.from_matrix([list(row) for row in embedding.integer_row_basis])
    transform = IntegerMatrix.identity(dimension)
    try:  # API details vary between fpylll releases; never accept an unverified transform.
        BKZ.reduction(basis, BKZ.Param(block_size=block_size), U=transform)
    except (TypeError, ValueError, RuntimeError):
        return None
    reduced_rows = tuple(
        tuple(int(basis[i, j]) for j in range(dimension)) for i in range(dimension)
    )
    transform_rows = tuple(
        tuple(int(transform[i, j]) for j in range(dimension)) for i in range(dimension)
    )
    for i in range(dimension):
        reconstructed = tuple(
            sum(transform_rows[i][k] * embedding.integer_row_basis[k][j] for k in range(dimension))
            for j in range(dimension)
        )
        if reconstructed != reduced_rows[i]:
            return None
    return LLLReduction(
        reduced_rows=reduced_rows,
        transform_rows=transform_rows,
        delta=Fraction(99, 100),
        backend=f"fpylll.BKZ(block_size={block_size}); transform verified",
    )


def bkz_or_deterministic_surrogate_baseline(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    modulus: int,
    *,
    block_size: int = 6,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    budget: RecoveryBudget = RecoveryBudget(),
) -> RecoveryResult:
    """BKZ when verified fpylll support exists; otherwise a named surrogate."""

    block_size = _as_int(block_size, "block_size")
    if block_size < 2:
        raise ValueError("block_size must be at least two")
    start = perf_counter()
    embedding = build_augmented_lattice(
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        require_regev_sample_count=True,
    )
    if embedding.dimension != len(family.pairs):
        raise ValueError("sample dimension does not match the rooted family")
    reduction = _verified_fpylll_bkz_reduction(embedding, block_size)
    if reduction is not None:
        strategy = "baseline_verified_fpylll_BKZ_plus_bounded_enumeration"
        interpretation = "Verified fpylll BKZ transform followed by the common node-bounded search."
        search_budget = budget
    else:
        reduction = lll_reduce_augmented_lattice(embedding, delta=Fraction(99, 100))
        reduction = replace(
            reduction,
            backend=(
                "deterministic strong SymPy LLL(delta=99/100) + bounded "
                f"block-combination search(block_size={block_size}); NOT BKZ"
            ),
        )
        strategy = "baseline_deterministic_strong_LLL_block_surrogate_NOT_BKZ"
        interpretation = (
            "No transform-verified BKZ backend was available; this is a deterministic "
            "strong-LLL/block-search surrogate and is not reported as BKZ."
        )
        search_budget = replace(
            budget,
            max_support=min(budget.max_support or block_size, block_size),
        )
    result = enumerate_reduced_basis_combinations(
        family,
        embedding,
        reduction,
        budget=search_budget,
        strategy=strategy,
        ordering="exact_embedding_norm",
        reductions=1,
        started_at=start,
    )
    return replace(result, interpretation=f"{result.interpretation} {interpretation}")


def matched_cost_recovery_suite(
    family: RootedBaseFamily,
    samples: Sequence[Sequence[int]],
    extra_sample_pool: Sequence[Sequence[int]],
    modulus: int,
    *,
    extra_count: int,
    seed: int,
    scale: int | Fraction | None = None,
    noise_bound: int | Fraction | None = None,
    budget: RecoveryBudget = RecoveryBudget(),
    seed_l0_directions: Sequence[Sequence[int]] = (),
    block_size: int = 6,
    relation_lift: RelationLift | None = None,
    quotient_key: QuotientKey | None = None,
) -> MatchedCostRecoveryComparison:
    """Run A, B, C, and three baselines with the same combination-node cap.

    The common cap matches the dominant bounded-enumeration work.  Reduction
    runtime and memory can differ (especially when genuine samples are added),
    so those costs are reported rather than declared equal.
    """

    standard = standard_lll_enumeration_baseline(
        family, samples, modulus, scale=scale, noise_bound=noise_bound, budget=budget
    )
    intervention_a = short_combination_recovery(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        budget=budget,
        relation_lift=relation_lift,
        quotient_key=quotient_key,
    )
    intervention_b = exact_quotient_deduplicated_recovery(
        family,
        samples,
        modulus,
        verified_l0_directions=seed_l0_directions,
        scale=scale,
        noise_bound=noise_bound,
        budget=budget,
        relation_lift=relation_lift,
    )
    intervention_c = adaptive_l0_suppression_recovery(
        family,
        samples,
        modulus,
        scale=scale,
        noise_bound=noise_bound,
        budget=budget,
        seed_l0_directions=seed_l0_directions,
        relation_lift=relation_lift,
        quotient_key=quotient_key,
    )
    extra = random_extra_samples_baseline(
        family,
        samples,
        extra_sample_pool,
        modulus,
        extra_count=extra_count,
        seed=seed,
        scale=scale,
        noise_bound=noise_bound,
        budget=budget,
    )
    bkz_or_surrogate = bkz_or_deterministic_surrogate_baseline(
        family,
        samples,
        modulus,
        block_size=block_size,
        scale=scale,
        noise_bound=noise_bound,
        budget=budget,
    )
    return MatchedCostRecoveryComparison(
        budget=budget,
        matching_rule=(
            "All six arms use the same max_nodes, coefficient bound, and requested "
            "row cap. Reduction count/backend, generated ordering nodes, runtime, and "
            "memory are reported separately; they are not assumed equal."
        ),
        results=(
            standard,
            intervention_a,
            intervention_b,
            intervention_c,
            extra,
            bkz_or_surrogate,
        ),
    )
